name: Upload Production MorpheusMp3ToMp4

# on:
#   [push]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install, build
      run: |
        yarn --production
        yarn zip
    - name: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws lambda update-function-code \
            --zip-file fileb://build.zip \
            --function-name arn:aws:lambda:us-east-1:125450506459:function:MorpheusMp3ToMp4 \
            --region us-east-1